### ISSUE TITLE
How do you fetch the download links?

### ISSUE THREAD

**Issue by sapioit** [electron-userland/electron-download#11]
Hello,

Could you, please, tell me how do you (if you do) fetch the list of versions, used to download the binaries?

Edit: I just found this in index.js ... my question is what would happen if the given version is non-existent (as in: a random version)?

     var filename = 'electron-v' + version + '-' + platform + '-' + arch + (symbols ? '-symbols' : '') + '.zip'
       var url = process.env.ELECTRON_MIRROR || opts.mirror || 'https://github.com/atom/electron/releases/download/v'
       url += version + '/electron-v' + version + '-' + platform + '-' + arch + (symbols ? '-symbols' : '') + '.zip'

**Comment by RnbWd** [comment]
It just throws an error :boom:

> Error: GET https://github.com/atom/electron/releases/download/v0.34.4/electron-v0.34.4-xxx-xxx.zip returned 404

**Comment by sapioit** [comment]
Ow, thanks! I was looking for a way to get the list of versions, for making a GUI alternative for packaging Electron 
apps...

**Comment by RnbWd** [comment]
Check out the [electron releases](https://github.com/atom/electron/releases) and [electron-prebuilt releases](https://github.com/mafintosh/electron-prebuilt/releases), maybe you can turn that into a gui?

**Comment by RnbWd** [comment]
I just downloaded the electron repo and used `git tag` to generate the list:

````
v0.1.0
v0.1.1
v0.1.2
v0.1.3
v0.1.4
v0.1.5
v0.1.6
v0.1.7
v0.1.8
v0.10.0
v0.10.1
v0.10.2
v0.10.3
v0.10.4
v0.10.5
v0.10.6
v0.10.7
v0.11.0
v0.11.1
v0.11.10
v0.11.2
v0.11.3
v0.11.4
v0.11.5
v0.11.6
v0.11.7
v0.11.8
v0.11.9
v0.12.0
v0.12.1
v0.12.2
v0.12.3
v0.12.4
v0.12.5
v0.12.6
v0.12.7
v0.13.0
v0.13.1
v0.13.2
v0.13.3
v0.14.0
v0.14.1
v0.14.2
v0.14.3
v0.15.0
v0.15.1
v0.15.2
v0.15.3
v0.15.4
v0.15.5
v0.15.6
v0.15.7
v0.15.8
v0.15.9
v0.16.0
v0.16.1
v0.16.2
v0.16.3
v0.17.0
v0.17.1
v0.17.2
v0.18.0
v0.18.1
v0.18.2
v0.19.0
v0.19.1
v0.19.2
v0.19.3
v0.19.4
v0.19.5
v0.2.0
v0.2.1
v0.20.0
v0.20.1
v0.20.2
v0.20.3
v0.20.4
v0.20.5
v0.20.6
v0.20.7
v0.20.8
v0.21.0
v0.21.1
v0.21.2
v0.21.3
v0.22.0
v0.22.1
v0.22.2
v0.22.3
v0.23.0
v0.24.0
v0.25.0
v0.25.1
v0.25.2
v0.25.3
v0.26.0
v0.26.1
v0.27.0
v0.27.1
v0.27.2
v0.27.3
v0.28.0
v0.28.1
v0.28.2
v0.28.3
v0.29.0
v0.29.1
v0.29.2
v0.3.0
v0.3.1
v0.3.2
v0.3.3
v0.3.4
v0.3.5
v0.30.0
v0.30.1
v0.30.2
v0.30.3
v0.30.4
v0.30.5
v0.30.6
v0.30.7
v0.30.8
v0.31.0
v0.31.1
v0.31.2
v0.32.0
v0.32.1
v0.32.2
v0.32.3
v0.33.0
v0.33.1
v0.33.2
v0.33.3
v0.33.4
v0.33.5
v0.33.6
v0.33.7
v0.33.8
v0.33.9
v0.34.0
v0.34.1
v0.34.2
v0.34.3
v0.4.0
v0.4.1
v0.4.2
v0.4.3
v0.4.4
v0.4.5
v0.4.6
v0.4.7
v0.4.8
v0.4.9
v0.5.0
v0.5.1
v0.5.2
v0.5.3
v0.5.4
v0.6.0
v0.6.1
v0.6.10
v0.6.11
v0.6.12
v0.6.2
v0.6.3
v0.6.4
v0.6.5
v0.6.6
v0.6.7
v0.6.8
v0.6.9
v0.7.0
v0.7.1
v0.7.2
v0.7.3
v0.7.4
v0.7.5
v0.7.6
v0.8.0
v0.8.1
v0.8.2
v0.8.3
v0.8.4
v0.8.5
v0.8.6
v0.8.7
v0.9.0
v0.9.1
v0.9.2
v0.9.3
v0.9.5
````
I'm down to help work on a gui if you're interested :), but I think the issue could closed.

**Comment by sapioit** [comment]
Oh, I found a something useful in the API... which will, thereby, support the future versions, as well...
https://api.github.com/repos/atom/electron/releases
https://api.github.com/repos/mafintosh/electron-prebuilt/releases
And I only need the "tag_name" from the JSON array...

So with a few lines of cod, I could get the list of versions be up to date, no matter when a new version pops up....
Now I'm thinking of using electron itself, for deploying the app on the 3 supported platforms... than find a way to parse JSON in JS(I don't have a lot of experience with JS, since I'm in the first semester of my second year of Computer Science Bachelor classes), make a tar archive with node/js, find how to get the user navigate to and choose a folder (to be packed) and the tags Electron supports, in package.json... The interface is pretty easy, since there are tutorials... 

For those interested who see this issue, look for [Colliderr](https://github.com/sapioit/Colliderr) (not a typo, but brandability and searchability - we all know it's a pain to google something electron or atom, without mentioning it's the software we're reffering to...)

**Comment by kevinsawicki** [comment]
> Oh, I found a something useful in the API... which will, thereby, support the future versions, as well...

Closing this out since it seems resolved now.
