### ISSUE TITLE
Save cached releases to standard directories

### ISSUE THREAD

**Issue by Siilwyn** [electron-userland/electron-download#24]
Instead of placing the release archives in the home directory they should be placed in the appropriate directory per OS. I've done the same for [Greenkeeper's RC](https://github.com/greenkeeperio/rc/pull/3) so I'd like to create a PR for it.

Before doing that I'd like to know if there are any special things I should take into consideration and if the core contributors are on board with this so I don't do it in vain. :)

**Comment by malept** [comment]
What do you propose to do with the existing cache directory? Is that still taken into account?

**Comment by Siilwyn** [comment]
We could use the old location if it exists or move the old location to the new location. At Greenkeeper the moving is done. Both have their own pros and cons.

**Comment by Siilwyn** [comment]
@malept any preference for one of the solutions?

**Comment by malept** [comment]
I would prefer moving it.

**Comment by develar** [comment]
@Siilwyn I see error in your merged changes, that leads to https://github.com/electron-userland/electron-download/pull/47#issuecomment-292803245

Code
```
const oldLocation = path.join(os.homedir(), './.electron', this.filename)
    if (pathExists.sync(oldLocation)) {
      return oldLocation
    }
```

in the `cachedZip`

But! We call `cachedZip` in the `ensureCacheDir` twice — one for check, and another one in the call `downloadZip`. So, 2 sync calls are performed, and latter can lead to race conditions — `downloadZip` must  download only to a new location.

In version of electron-download that used by electron-builder, I will remove this code for now.

**Comment by Siilwyn** [comment]
Oh that is bad. :/

@develar could you expand your explanation, I don't quite follow.

**Comment by develar** [comment]
@Siilwyn downloadZip calls cachedZip, but cachedZip will check and return old location. Not evident how does it lead to error, but in any case it is not good — cachedZip should return constant result (based on options) and old location should be checked in another place.

**Comment by Siilwyn** [comment]
The function that checks if the zip file is already cached sounds like the appropriate place for this check to me. Where would you place it?

**Comment by Siilwyn** [comment]
@develar [moving the logic to the directory location](https://github.com/electron-userland/electron-download/compare/master...Siilwyn:fix-fallback-location) seems to fix it. Could you confirm this?
