### ISSUE TITLE
Conversion to ES6 should have resulted in a major version change

### ISSUE THREAD

**Issue by kgryte** [electron-userland/electron-download#28]
Due to ES6 conversion, this module no longer works in Node.js environments `< 4`. As a result, while `electron` is perfectly usable in earlier environments, downloading `electron` no longer works. This is causing builds to fail during the `npm install` process.

The workaround here, in order to support earlier environments, would be to either a) revert back to ES5 or b) use `babel` or some other transpiler to transpile the ES6 code to ES5 pre-publish.

**Comment by malept** [comment]
Personally, I'd be more inclined to yank 2.2.0 and publish 3.0.0.

**Comment by kgryte** [comment]
@malept I am not convinced that is optimal.

a) If `electron` wants to continue supporting installations via `npm` install, then, in order to support installing on earlier Node.js versions (`electron-prebuilt` currently runs builds on Node.js versions `0.10`, `0.12`, and `iojs`), then the `electron` module cannot use the updated `electron-download` module. And any future bug fixes, etc, will need to be back ported to a separately maintained version. This electron-userland split seems to entail more work than need be.

b) Not clear why the module was converted to ES2015 in the first place. If the intent is to simply download `electron`, not sure why this module would want to limit the possible installation environments and only target newer Node.js versions.

c) But if ES2015 is deemed necessary, using sthg like `babel` to transpile pre-publish is common practice and would allow catering to both demands.

**Comment by kgryte** [comment]
Related issue: rtsao/unitest#13

**Comment by malept** [comment]
To your points:

> a) If electron wants to continue supporting installations via npm install, then, in order to support installing on earlier Node.js versions (electron-prebuilt currently runs builds on Node.js versions 0.10, 0.12, and iojs), then the electron module cannot use the updated electron-download module.

I have a [pull request](https://github.com/electron-userland/electron-prebuilt/pull/189) that I made yesterday that updates Travis to instead run builds on Node >= 4 (and I should also update it to require electron-download 3.0.0, once that's released).

> b) Not clear why the module was converted to ES2015 in the first place. If the intent is to simply download electron, not sure why this module would want to limit the possible installation environments and only target newer Node.js versions.

The code accrued a lot of technical debt, which made it rather non-trivial to add a feature (namely, [checksum support](https://github.com/electron-userland/electron-download/pull/25)). Adding the feature would have taken about the same amount of time with or without the refactor, so I chose making the code clearer.

> c) But if ES2015 is deemed necessary, using sthg like babel to transpile pre-publish is common practice and would allow catering to both demands.

I would personally be more amenable to this suggestion if babel weren't so heavyweight.

**Comment by kgryte** [comment]
@malept 

Re: b. Fair enough. Although nothing about checksum support demands ES2015 features and thus necessitates breaking changes. 

Re: a) and electron-userland/electron-prebuilt#189. I fail to see why dropping support for prior Node.js versions is a good thing. `0.12` is still an officially supported version through the end of the year. `0.10` (officially supported until October) still has considerable use in enterprise deployments. In particular, `electron` should not be forced to undergo a breaking change simply to accommodate this module's decision to only support ES2015 environments.

Re: c. While I am sympathize with the desire to clean-up and modernize a code base, ultimately that needs to be balanced with a code base's use in the broader context. Here, that context is `electron`, which should be capable of being installed alongside any version of Node.js `>=0.10`. And I'd argue that `electron` and its supported install environments should dictate the supported install environments of associated tooling, not the other way around. So, in this case, the decision to clean-up should consider this constraint and view using sthg like `babel` as part of the cost of modernization.
