### ISSUE TITLE
Permission Denied when Deploying on AWS and creating the temporary directory

### ISSUE THREAD

**Issue by QuentinDela** [electron-userland/electron-download#39]
Hello,

I am trying to run NightmareJS on Elastic Beanstalk and I keep having an issue with Electron.

Error: EACCES: permission denied, mkdir '/tmp/deployment/application/node_modules/electron/electron-tmp-download-2233-1478789913678'

Here are the full logs: https://gist.github.com/QuentinDela/49e824c5889e14e899eafbe850d23055

Here is the related issue on nightmare:
https://github.com/electron/electron/issues/7938

Would you have any ideas on how to fix this?

Thanks,

**Comment by MarshallOfSound** [comment]
I believe this has been fixed thanks to #47
