### ISSUE TITLE
GitHub download ratios

### ISSUE THREAD

**Issue by ThorstenHans** [electron-userland/electron-download#48]
Short question, due the fact that `electron-download` is pulling releases from `https://github.com/electron/electron/releases/download/v` do the request may run into request limits? 

Background of the question is that I'm frequently using `electron-packager` for workshops. When multiple attendees use the same IP address to download the releases, github may restrict access for an hour. 

Unfortunately there is no option or provide an API token. (`gulp-atom-electron` allows to specify an API_Token for example)

Did anyone run into this issue?

**Comment by MarshallOfSound** [comment]
`electron-download` never hits the GitHub API itself (only direct download URL's) so there should be no limit (at least there is no documented limit)
