### ISSUE TITLE
please follow redirect

### ISSUE THREAD

**Issue by Zougi** [electron-userland/electron-download#49]
Hi, I'd like to download electron from a location on our corporate sonatype nexus.
The uri returned by nexus gives a redirect (302). Redirect is not followed. package is therefore not downloaded even if it exists.

I get the following error:

```sh
npm i electron@1.4.15 --save-dev --reg
http://internalrepository.addr.corp:8081/nexus/content/groups/build.milestones.npm/                           
(node:11289) fs: re-evaluating native module sources is not supported.
If you are using the graceful-fs module, please update it to a more
recent version.

> electron@1.4.15 postinstall /home/me/wing/node_modules/electron
> node install.js

/home/me/wing/node_modules/electron/install.js:46
  throw err
  ^

Error: Failed to find Electron v1.4.15 for linux-x64 at
http://internalrepository.addr.corp:8081/nexus/service/local/repositories/3rd-party.releases.manual-uploads.hosted/content/io/atom/electron/download/electron/electron/1.4.15/electron-1.4.15-linux-x64.zip
    at Request.<anonymous>
(/home/I301937/wing/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse
(/home/I301937/wing/node_modules/request/request.js:1074:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming]
(_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
```

However _http://internalrepository.addr.corp:8081/nexus/service/local/repositories/3rd-party.releases.manual-uploads.hosted/content/io/atom/electron/download/electron/electron/1.4.15/electron-1.4.15-linux-x64.zip_ does exist.

FYI: I use the following env variables to specify a different electron uri:
ELECTRON_CUSTOM_FILENAME="electron-1.4.15-linux-x64.zip"
ELECTRON_MIRROR="http://internalrepository.addr.corp:8081/nexus/service/local/repositories/3rd-party.releases.manual-uploads.hosted/content/io/atom/electron/download/electron/electron/1.4.15"

**Comment by MarshallOfSound** [comment]
`next` is changing how downloading works and now uses `got` which follows redirects
