### ISSUE TITLE
disable checksum

### ISSUE THREAD

**Issue by Zougi** [electron-userland/electron-download#51]
Could it be possible to disable checksum when we tell electron-download to download electron from a private location? I'm creating a PR to detail this change

**Comment by craxal** [comment]
I noticed that a failed checksum has a very bad habit of deleting existing Electron files. While this may be ok for files `electron-download` retrieved itself, this does not work for files I put into the cache location manually, such as files from a private build of Electron. **Failed checksums should not blindly delete files from the cache!**

**Comment by eanders-MS** [comment]
+1 for option to disable checksums, please. I'm using a custom electron build, and do not generate SHASUMS256.txt. This requirement is blocking me from using electron-download to provide the build to electron-builder.

**Comment by eanders-MS** [comment]
Oh, interesting, `electron-builder` uses `electron-download-tf`. I was perusing its implementation in node_modules in order to make a local patch to unblock my work, and noticed it has an possibly undocumented option to disable checksum verification that isn't reflected in this codebase:
```javascript
  get verifyChecksumNeeded () {
    return this.opts.verifyChecksum !== false && semver.gte(this.version, '1.3.2')
  }
```

**Comment by craxal** [comment]
Is there any news on this issue?

I'm using a forked build of Electron, and this checksum issue is blocking me. I'm stuck using a very old version of `electron-packager` (7.7.0), and it doesn't appear to be working anymore with newer versions of my fork based on recent (1.8.*) versions of Electron.

**Comment by develar** [comment]
@eanders-MS It is documented now — https://www.electron.build/configuration/configuration `verifyChecksum`
@craxal You can use electron-builder. Another possible workaround — you can use `ELECTRON_CACHE` env, but problem is that latest sources of electron-download not published on npm.

I will try to find time to prepare PR to add `verifyChecksum` option.

**Comment by eanders-MS** [comment]
@craxal I ended up generating the checksums myself. Here's a Power Shell script that does this, in case it helps:
```
Get-FileHash electron* -Algorithm SHA256 | foreach { "{0} *{1}" -f $_.Hash.ToLower(), [System.IO.Path]::GetFileName($_.Path) } | Out-String | %{ $_.Replace("`r`n","`n") } | Out-File -Encoding ASCII -filepath SHASUMS256.txt
```

**Comment by craxal** [comment]
@develar Learning about and integrating a whole new packaging module is pretty expensive, isn't it? Are there any advantages to using `electron-builder` over `electron-packager`? What do they do differently?

@eanders-MS Doesn't this sort of defeat the whole point of the checksum? The purpose of the checksum is to make sure the package you downloaded from wherever is intact and unchanged. Generating it yourself locally just makes the whole checksum process superfluous.

**Comment by eanders-MS** [comment]
@craxal It would certainly defeat the point when downloading Electron from an external source. In my case, we use an internal custom build of Electron, so it's trusted, but it was necessary to compute a new checksum for it.

**Comment by MarshallOfSound** [comment]
@eanders-MS That checksum should be generated when you build your version of Electron though and hosted with your Electron build.  Otherwise it's just fake safety 😄
