### ISSUE TITLE
Throw error when cached Electron isn't found instead of downloading by default

### ISSUE THREAD

**Issue by craxal** [electron-userland/electron-download#57]
I use a private build of Electron that I store on my local machine, and I use `electron-packager` to package my application. To use my private Electron, I set the `cache` option.

Debugging my build scripts was very cumbersome, because `electron-download` gave no indication of whether it could find the Electron build in the cache location or not. If it can't find Electron, it defaults to downloading public releases.

This is not what I want! I don't want the publicly available bits. I'd rather `electron-download` throw an error that I can catch and act on quickly.

electron-userland/electron-packager#187

**Comment by MarshallOfSound** [comment]
Adding a new options `autoDownload` and defaulting to `true` would be a valid solution to this issue

**Comment by craxal** [comment]
I should mention that the checksum process makes using private Electron builds cumbersome, as it attempts to download and check a SHASUM file against the private Electron. Since private builds won't match public ones, this is obviously going to throw an error.
