### ISSUE TITLE
Consider using `got`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [electron-userland/electron-download#63]
As opposed to `nugget`.  It has a significantly smaller dependency tree of [21 modules](http://npm.anvaka.com/#/view/2d/got) as opposed to [116](http://npm.anvaka.com/#/view/2d/nugget).

**Comment by develar** [comment]
👍  https://github.com/maxogden/nugget/issues/20

**Comment by MarshallOfSound** [comment]
`next` is now using `got` by default with the ability to provide your own custom downloader 👍
