### ISSUE TITLE
back port sumchecker 2.0.2 to 3.x

### ISSUE THREAD

**Issue by wojtkowiak** [electron-userland/electron-download#66]
Hello could you backport sumcheck upgrade to 3.x version?
On node 8 it not possible to download electron as I am getting:
`Error: Generated checksum for "chromedriver-v2.21-win32-x64.zip" did not match expected checksum.`

In sumchecker 2 it was fixed https://github.com/malept/sumchecker/issues/7

I see that:
```
+--  electron@1.7.9
| `--  electron-download@3.3.0
|   `--  sumchecker@1.3.1
```

but since electron has reverted the update to electron-download 4 for a reason (https://github.com/electron/electron/commit/6f3fdb6ae6b5b3a0e55696d80f88b8f680bc5eac) I am asking here 🙂

**Comment by malept** [comment]
The fix for Node 8 was backported in sumchecker 1.3.1: https://github.com/malept/sumchecker/releases/tag/v1.3.1

You should run `npm update` for electron-download.
