### ISSUE TITLE
nugget does not consider npm/yarn cafile property

### ISSUE THREAD

**Issue by sla89** [electron-userland/electron-download#67]
Hello together,

your dependency `nugget` does not consider the npm/yarn config property [cafile](https://docs.npmjs.com/misc/config#cafile) which is used in case you are using a self signed certificate chain. This issue is the reason why we have to set [strict-ssl=false](https://docs.npmjs.com/misc/config#strict-ssl). Other packages like `node-gyp` or `node-pre-gyp` are using `request` instead of `nugget` which handles the `cafile` property correctly.

The `nugget` team received a PR (maxogden/nugget#11) in 2015. Sadly there are no updates in the PR since then. They know about that issue and don't solve it.

Since there are some proposals around to either replace `nugget` (#53) or to use `got` (#63) I want to know how you will go on with the `nugget` topic. 

Thank you,
Stefan

**Comment by sla89** [comment]
@malept, @MarshallOfSound, @kevinsawicki friendly ping

**Comment by MarshallOfSound** [comment]
We now use `got` 👍 in `next`

**Comment by sla89** [comment]
Sorry for that very late response.
We have not updated to electron 9 (we were still on the old version that used the nugget module).

I am sorry to disappoint you but it does not work.

When you are using `got` you have to specify the `cafile` within the options object that you pass to `download`.  See https://github.com/sindresorhus/got/issues/293

**Comment by malept** [comment]
It should work with `got`. According to [`got`'s `options` docs](https://github.com/sindresorhus/got#options), it takes any option from `https.request`, which transitively includes any option from [`tls.createSecureContext`](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options), which in your case, `ca` is relevant. It'd look something like (untested):

```typescript
import { download } from '@electron/get';

await download('9.0.0', {
  downloadOptions: {
    ca: '/path/to/ca/file'
  }
});
```

**Comment by sla89** [comment]
Yes, but with your approach I have to additionally define a download script that depends on electron get... Currently `@electron/get` simply fails in my companies environment because it still does not consider the `npm` or `yarn` settings.

The solution is simple, if you want I can provide a merge request for it:
`@electron/get` simply has to consider what people are setting in their `npm` or `yarn` settings.

**Comment by MarshallOfSound** [comment]
> The solution is simple... @electron/get has to consider what people are setting in their npm or yarn settings (so many other modules capture this property....)

PRs are welcome
