### ISSUE TITLE
The 'cache' option is ignored when retrieving SHASUM file

### ISSUE THREAD

**Issue by craxal** [electron-userland/electron-download#71]
The `cache` options let's me specify a location on my local machine where `electron-download` will find an existing Electron package it should use instead of downloading it from somewhere. This works just fine.

However, this option is ignored when `electron-download` starts looking for the SHASUM file. Either the package should use the same `cache` location, or another option should be added.

**Comment by MarshallOfSound** [comment]
I'm pretty sure this is fixed in `next` 👍
