### ISSUE TITLE
The `mirror` options don't work for URL endpoints requiring credentials

### ISSUE THREAD

**Issue by craxal** [electron-userland/electron-download#72]
The `mirror`, `customDir`, and `customFilename` options let you specify a custom URL and path to download Electron packages from. For publicly available resources, this works fine.

This is insufficient for secure resources. For example, I can't download anything from a URL that requires authentication via a SAS token.

Techincally, I can use a SAS token by appending a query string to `customFilename`. This doesn't work, however, when attempting to download SHASUM files.

See #71 for a related issue.

**Comment by MarshallOfSound** [comment]
Closing this out as the downloader logic was rewritten as part of `next`
