### ISSUE TITLE
Error: Configuration is invalid.

### ISSUE THREAD

**Issue by pasupathy1611** [electron-userland/electron-download#76]
Using `cache` option instead of downloading the electron package and getting this error below.

![electrondownload](https://user-images.githubusercontent.com/19950170/42316459-80cc80b0-8067-11e8-9fef-320fc00d50b4.png)

Not able to find the option `version` from the link mentioned above.

These are the properties used in package.json
`"electronDownload": {
			"cache": "./conf/electron",
			"verifyChecksum": false
		}
`

**Comment by MarshallOfSound** [comment]
@pasupathy1611 That error is coming from `electron-builder` not this module 👍

**Comment by pasupathy1611** [comment]
sorry!! @MarshallOfSound
